#!/bin/sh -ef

. "$(dirname "$0")/config"

PATH_SEP=':'
if [ "${OS:-}" = "Windows_NT" ]; then
  PATH_SEP=';'
fi

PYTHONPATH="$PYTHON_RUNTIME_DIR${PATH_SEP}compiled/python${PATH_SEP}spec/python${PATH_SEP}spec/python/extra" PYTHONDONTWRITEBYTECODE=1 PYTHONDEVMODE=1 python -m unittest discover -s spec/python
